### ISSUE TITLE
Add "related posts" to each post

### ISSUE THREAD

**Issue by hbillings** [GSA/centers-of-excellence#138]
In conjunction with @vbitzer, determine what "relates" one post to another (tags, most likely, but perhaps also posts that relate to the same agency? posts that are in a series?)

For design reference, see related posts at the bottom of this page: https://18f.gsa.gov/2019/04/03/hcd-for-centralization-series-1-why-prioritizing-users-is-important/

**Comment by vbitzer** [comment]
Yes, I think this series could work just like that: https://coe.gsa.gov/2019/04/17/cx-update-9.html. But I would also like the ability to click on "cx" for example, and be able to access all of the articles with that tag. Just like the example you shared that includes "10x" "best practices" etc.
