### ISSUE TITLE
Icons are mangled on mobile for all Centers

### ISSUE THREAD

**Issue by vbitzer** [GSA/centers-of-excellence#153]
**https://coe.gsa.gov/coe/cloud-adoption.html**
![Image from iOS](https://user-images.githubusercontent.com/27738082/61305135-4847d900-a7b8-11e9-9fca-a3a0a8295a34.png)

**Comment by cantsin** [comment]
Maybe I'm missing something here, but these icons look fine to me. Did we want these icons to be smaller?

**Comment by vbitzer** [comment]
They look OK to me as well in the grand scheme of things, I think they need to be redesigned  @cantsin
