### ISSUE TITLE
Padding issues on our video

### ISSUE THREAD

**Issue by vbitzer** [GSA/centers-of-excellence#202]
![Screen Shot 2019-09-25 at 12 13 33 PM](https://user-images.githubusercontent.com/27738082/65619316-efea4000-df8d-11e9-996a-cea84034c939.png)

Checkout attached screenshot for this video: https://coe.gsa.gov/connect/contact-us.html#joinus

**Comment by vbitzer** [comment]
Fixed!

**Comment by vbitzer** [comment]
On Firefox, it shows up at the 3 second mark. Screenshot attached, black line shows on the far right.

**Comment by cantsin** [comment]
Interesting, I can't replicate. Using chrome or firefox on OSX. But I do notice the black line shows up when zoomed in, but there's not much we can do about that, as that is browser-specific.

**Comment by vbitzer** [comment]
> Interesting, I can't replicate. Using chrome or firefox on OSX. But I do notice the black line shows up when zoomed in, but there's not much we can do about that, as that is browser-specific.

Yes, that seems to be browser specific as we've tested in in a few versions. Thanks!
