### ISSUE TITLE
Thumbnail for coe.gsa.gov is broken

### ISSUE THREAD

**Issue by oghaffari** [GSA/centers-of-excellence#35]
When posting a link to the COE website in LinkedIn, the thumbnail preview that should show up does not with a broken image showing up in its place.

**Comment by oghaffari** [comment]
[Will be addressed shortly](https://github.com/18F/design-lab/issues/43).

**Comment by LindsayYoung** [comment]
Looks like this was fixed in https://github.com/GSA/centers-of-excellence/pull/48
