### ISSUE TITLE
Menu links don't collapse on IE

### ISSUE THREAD

**Issue by LindsayYoung** [GSA/centers-of-excellence#36]
Here is a screen shot of the menus that are all open when coming to the site using IE (I don't know what version of IE I am passing this along)

![image](https://user-images.githubusercontent.com/4406333/51871954-d83ab900-2325-11e9-8671-378c2f7f32e9.png)

**Comment by hbillings** [comment]
I've seen this happen when the client doesn't support Javascript or has it turned off. (USWDS dropdowns are expanded by default and collapsed once JS loads. The thinking behind this is that if a browser doesn't have JS enabled, they can still navigate, but it's... not really a great solution.)

**Comment by vbitzer** [comment]
I suppose we can close this too?
